version: "3.3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres-volume/:/var/lib/postgresql/data
    env_file:
      - .env.compose
#    environment:
#      - POSTGRES_PASSWORD
#      - POSTGRES_USER
    networks:
      - cs-network

  csb:
    image: briangraj/csb:latest
    ports:
      - "8080:8080"
    volumes:
      - ./dataset/:/myapp/dataset
    env_file:
      - .env.compose
#    environment:
#      - RAILS_ENV
#      - PORT
#      - DATABASE_URL
#      - DATASET_URL
    depends_on:
      - postgres
    networks:
      - cs-network

  csf:
    image: briangraj/csf:latest
    ports:
      - "3000:80"

networks:
  cs-network: